package _Root.patches.templates

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Template
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a template with uuid = '49acc8d7-5d31-4672-8bbf-3362cfa82319' (id = 'AwesomeApi_K8sPublish')
in the project with uuid = '90df4be5-63a3-4908-b044-6bdb7f9b791d' and delete the patch script.
*/
create("90df4be5-63a3-4908-b044-6bdb7f9b791d", Template({
    uuid = "49acc8d7-5d31-4672-8bbf-3362cfa82319"
    id = "AwesomeApi_K8sPublish"
    name = "K8S publish"

    type = BuildTypeSettings.Type.COMPOSITE

    vcs {
        showDependenciesChanges = true
    }

    dependencies {
        dependency("AwesomeApi_2DynamicSecurityTesting") {
            snapshot {
                reuseBuilds = ReuseBuilds.ANY
                onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency("AwesomeApi_3Publish") {
            snapshot {
                reuseBuilds = ReuseBuilds.ANY
                onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency("AwesomeApi_Build") {
            snapshot {
                reuseBuilds = ReuseBuilds.ANY
                onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
    }
}))

